// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfEGo37KIFzYMs5uv29J_cBDSsveCwhGI',
    appId: '1:525705437311:web:cd24a9e1fcc7d917585f4a',
    messagingSenderId: '525705437311',
    projectId: 'oasish-65f81',
    authDomain: 'oasish-65f81.firebaseapp.com',
    storageBucket: 'oasish-65f81.firebasestorage.app',
    measurementId: 'G-Z8RS120M9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWnKA3IIkkkWdl8mWVPXFSQzl1vgdLkLE',
    appId: '1:525705437311:android:a436a4faf38d3cc5585f4a',
    messagingSenderId: '525705437311',
    projectId: 'oasish-65f81',
    storageBucket: 'oasish-65f81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFYmVT48ywp6VqlAwdb0ZCM55kA2IRy08',
    appId: '1:525705437311:ios:0189ae3532f1fb3f585f4a',
    messagingSenderId: '525705437311',
    projectId: 'oasish-65f81',
    storageBucket: 'oasish-65f81.firebasestorage.app',
    iosBundleId: 'com.example.hrisFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFYmVT48ywp6VqlAwdb0ZCM55kA2IRy08',
    appId: '1:525705437311:ios:0189ae3532f1fb3f585f4a',
    messagingSenderId: '525705437311',
    projectId: 'oasish-65f81',
    storageBucket: 'oasish-65f81.firebasestorage.app',
    iosBundleId: 'com.example.hrisFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfEGo37KIFzYMs5uv29J_cBDSsveCwhGI',
    appId: '1:525705437311:web:e0270cecf8ce71c6585f4a',
    messagingSenderId: '525705437311',
    projectId: 'oasish-65f81',
    authDomain: 'oasish-65f81.firebaseapp.com',
    storageBucket: 'oasish-65f81.firebasestorage.app',
    measurementId: 'G-DSS270XZEK',
  );
}
